other

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -18,13 +18,6 @@ ENV_DIR=$3
 CRT="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
 DATABASE_URL="mysql://root:password@localhost:3306/app"
 WDIR=.heroku/mysql
-{ # try
-  sudo ln -s /usr/lib/libncursesw.so.6.0 /usr/lib/libncurses.so.5
-  sudo ln -s /usr/lib/libncursesw.so.6.0 /usr/lib/libtinfo.so.5
-  echo 'libncursesw.so.6.0 <= libncurses.so.5'
-} || { # catch
-  echo 'libncursesw.so.6.0 not found'
-}
 echo "-----> MySQL Install $BINFILE"
 mkdir -p $BUILD_DIR/.heroku/mysql
 mkdir -p $BUILD_DIR/.heroku/mysql/data
@@ -36,6 +29,12 @@ rm $BINFILE
 chmod +x $CRT/../scripts/*.sh
 
 CLIENT="$BUILD_DIR/$WDIR/bin"
+{ # try
+  ln -s /usr/lib/libncursesw.so.6.0 $BUILD_DIR/$WDIR/lib/libncurses.so.5 && ln -s /usr/lib/libncursesw.so.6.0 $BUILD_DIR/$WDIR/lib/libtinfo.so.5
+  echo 'libncursesw.so.6.0 <= libncurses.so.5'
+} || { # catch
+  echo 'libncursesw.so.6.0 not found'
+}
 cp $CRT/../scripts/* $CLIENT
 
 cat > $BUILD_DIR/env.sh <<EOF
